services:
  postgres_auth:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5437:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - novalink_network

  auth_api:
    build: .
    ports:
      - "8007:8000"
    depends_on:
      - postgres_auth
    environment:
      POSTGRES_HOST: postgres_users
      POSTGRES_DB: users_db
      POSTGRES_USER: novalink
      POSTGRES_PASSWORD: novalinkpwd
    networks:
      - novalink_network

volumes:
  postgres_auth_data:
    name: postgres_auth_data

networks:
  novalink_network:
    external: true
