services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: novalink-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  redis:
    image: redis:7-alpine
    container_name: novalink-redis
    ports:
      - "6379:6379"

  skills-worker:
    build: 
      context: .
    container_name: novalink-events-skills
    command: python services/skills/skills.py run
    restart: always
    depends_on:
      - rabbitmq
      - redis

  users-worker:
    build: 
      context: .
    container_name: novalink-events-users
    command: python services/users/users.py run
    restart: always
    depends_on:
      - rabbitmq
      - redis

  notifications-worker:
    build: 
      context: .
    container_name: novalink-events-notifications
    command: python services/notifications/notifications.py run
    restart: always
    depends_on:
      - rabbitmq
      - redis
