apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notifications-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-notifications
spec:
  selector:
    matchLabels:
      app: postgres-notifications
  template:
    metadata:
      labels:
        app: postgres-notifications
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "novalink_user"
        - name: POSTGRES_PASSWORD
          value: "novalink_password"
        - name: POSTGRES_DB
          value: "notifications_db"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: notifications-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-notifications
spec:
  selector:
    app: postgres-notifications
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
spec:
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
      - name: api
        image: notifications-api:latest
        imagePullPolicy: IfNotPresent
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8004"]
        env:
        - name: DB_USER
          value: "novalink_user"
        - name: DB_PASSWORD
          value: "novalink_password"
        - name: DB_HOST
          value: "postgres-notifications" # ¡Aquí ocurre la magia de red interna de K8s!
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "notifications_db"
        - name: DB_ECHO
          value: "false"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "8004"
        ports:
        - containerPort: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-api
spec:
  selector:
    app: notifications-api
  ports:
  - port: 8004
    targetPort: 8004