version: "3.9"

services:

  db:
    image: postgres:15-alpine
    container_name: users_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"       # Opcional: exponer al host para debugging
    networks:
      - users_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: users_api
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy   # Espera que Postgres esté listo
    networks:
      - users_net
      - shared_net                  # Red compartida con otros microservicios

volumes:
  postgres_data:

networks:
  users_net:
    driver: bridge
  shared_net:
    external: true                  # Red externa compartida con otros servicios