services:
  postgres_users:
    image: postgres:15-alpine
    container_name: postgres_users
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - novalink_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  users_api:
    build: .
    container_name: users_api
    restart: always
    env_file: .env
    ports:
      - "8001:8000"
    depends_on:
      postgres_users:
        condition: service_healthy
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST:-postgres_users}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME}
      DB_ECHO: ${DB_ECHO}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-novalink-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST:-/}
    networks:
      - novalink_network

  users_worker:
    build: .
    container_name: users_worker
    restart: always
    env_file: .env
    depends_on:
      postgres_users:
        condition: service_healthy
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres_users
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_ECHO: ${DB_ECHO}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-novalink-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST:-/}
    volumes:
      - .:/app
    networks:
      - novalink_network
    command: python -m app.infrastructure.event_worker run

volumes:
  postgres_users_data:

networks:
  novalink_network:
    external: true
