services:
  postgres_users:
    image: postgres:15-alpine
    container_name: postgres_users
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - novalink_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  users_api:
    build: .
    container_name: users_api
    restart: always
    env_file: .env
    ports:
      - "8001:8000"
    depends_on:
      postgres_users:
        condition: service_healthy
    networks:
      - novalink_network

volumes:
  postgres_users_data:

networks:
  novalink_network:
    driver: bridge
